#!/usr/bin/env bash

USBIMG=usb.img
UFSIMG=ufs.img

function devargs() {
    D=$1
    ARGS=
    case $D in
        "usb-storage")
            if [ ! -f $USBIMG ]; then
                dd if=/dev/zero of=$USBIMG bs=1k count=1024 >&2
                mkfs -t ext4 $USBIMG >&2
            fi
            ARGS="-drive if=none,id=usbstick,format=raw,file=$USBIMG \
                  -usb                                               \
                  -device usb-ehci,id=ehci                           \
                  -device usb-storage,bus=ehci.0,drive=usbstick"
         ;;
        "ufs")
            if [ ! -f $UFSIMG ]; then
                dd if=/dev/zero of=$UFSIMG bs=1k count=1024 >&2
                mkfs -t ext4 $UFSIMG >&2
            fi
            ARGS="-drive if=none,id=ufslu0,format=raw,file=$UFSIMG \
                  -device ufs,id=ufs0,nutrs=32,nutmrs=8            \
                  -device ufs-lu,drive=ufslu0,bus=ufs0"
         ;;
    esac

    echo $ARGS
}

OPTS=
QEMU_OPTS=
BOOTARGS=
ARCH=
while getopts ":ka:d:" opt
do
    case $opt in
        a)
            ARCH=$OPTARG
        ;;
        d)
            args=`devargs $OPTARG`
            if [ -z "$args" ]; then
                echo "Invalid device option $OPTARG"
                exit 1
            fi
            QEMU_OPTS+=$args
        ;;
        k)
            BOOTARGS+="crashkernel=256M"
            QEMU_OPTS+="-device vmcoreinfo"
        ;;
    esac
done
shift $((OPTIND - 1))

if [[ -n $ARCH ]]; then
    OPT+=" --arch $ARCH"
fi

if [[ ! -z $BOOTARGS ]]; then
    OPT+=" --append='$BOOTARGS'"
fi

if [[ ! -z $QEMU_OPTS ]]; then
    OPT+=" -o='$QEMU_OPTS'"
fi

# Run vng with bash shell by default, just for faster booting
OPT+=" --shell /bin/bash"

echo "Running vng with options: $OPT $@"
eval "vng $OPT $@"
